version: 2.1

jobs:
  build:
    working_directory: /home/xub/Desktop/flaskapp
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 run.py
  test:
    working_directory: /home/xub/Desktop/flaskapp/tests
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main_test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
