version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - command: | 
        python3 -m virtualenv venv
        ./venv/bin/activate
        pip install -r requirements.txt
      - run: python3 run.py
  test:
    working_directory: ~/circleci-python/tests
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main_test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
